# jenkins-ec2-agents-policy.hcl
#
# Read-only access to agent keypairs generated by generate-and-store.sh, so ec2-deploy/Jenkinsfile
# can fetch the right private key by date_name at deploy time. Attach this alongside the existing
# jenkins-vault.hcl policy from project-8/vault-cmd/policies (that one still covers
# aws/creds/jenkins) - this repo only adds the KV path, it doesn't replace that policy.
path "secret/data/ec2-agents/*" {
  capabilities = ["read"]
}
